//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSFramework.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShopConfiguration
    {
        public long ShopId { get; set; }
        public string BgColor { get; set; }
        public string MenuColor { get; set; }
        public Nullable<int> LayoutId { get; set; }
        public string MenuTextColor { get; set; }
    }
}
